Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  
  ### Initial Configuration ###
  # Perform initial configuration for Vagrant
  # Enable and manage host entries using hostmanager plugin
  # This allows Vagrant to automatically update the hosts file on the host machine


  ### Nginx VM ###
  # Define and configure the Nginx virtual machine
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/bionic64"  # Use the Ubuntu Bionic64 box as the base
    web01.vm.hostname = "web01"  # Set the hostname of the virtual machine to web01
    web01.vm.network "private_network", ip: "192.168.56.11"  # Assign the private IP address 192.168.56.11 to the virtual machine
  end
  
  ### Tomcat VM ###
  # Define and configure the Tomcat virtual machine
  config.vm.define "app01" do |app01|
    app01.vm.box = "geerlingguy/centos7"  # Use the CentOS 7 box as the base
    app01.vm.hostname = "app01"  # Set the hostname of the virtual machine to app01
    app01.vm.network "private_network", ip: "192.168.56.12"  # Assign the private IP address 192.168.56.12 to the virtual machine
  end
   
  ### RabbitMQ VM ###
  # Define and configure the RabbitMQ virtual machine
  config.vm.define "rmq01" do |rmq01|
    rmq01.vm.box = "geerlingguy/centos7"  # Use the CentOS 7 box as the base
    rmq01.vm.hostname = "rmq01"  # Set the hostname of the virtual machine to rmq01
    rmq01.vm.network "private_network", ip: "192.168.56.16"  # Assign the private IP address 192.168.56.16 to the virtual machine
  end
  
  ### Memcache VM ###
  # Define and configure the Memcache virtual machine
  config.vm.define "mc01" do |mc01|
    mc01.vm.box = "geerlingguy/centos7"  # Use the CentOS 7 box as the base
    mc01.vm.hostname = "mc01"  # Set the hostname of the virtual machine to mc01
    mc01.vm.network "private_network", ip: "192.168.56.14"  # Assign the private IP address 192.168.56.14 to the virtual machine
  end
  
  ### DB VM ###
  # Define and configure the database virtual machine
  config.vm.define "db01" do |db01|
    db01.vm.box = "geerlingguy/centos7"  # Use the CentOS 7 box as the base
    db01.vm.hostname = "db01"  # Set the hostname of the virtual machine to db01
    db01.vm.network "private_network", ip: "192.168.56.15"  # Assign the private IP address 192.168.56.15 to the virtual machine
  end
end
